### ISSUE TITLE
Right Side of Hand Curve

### ISSUE THREAD

**Issue by Beta1457** [insideout-andrew/deckbuilder-framework#1]
The right side of the hand is noticeably lower on the screen than the left side. 

Only visual issue I saw from your demo, going to poke through the code later. Nice work so far!

**Comment by insideout-andrew** [comment]
Yes, this is a known bug documented at the bottom of the readme. I'm just not sure of the correct fix. 

`card.target_rotation` doesn't seem to be respecting the `card.pivot_offset`. 

Something about the interaction between `card.target_rotation` and `card.target_position` is messing it up. 

This is causing inconsistent rotations in curved hands.

**Comment by Beta1457** [comment]
I'll look into it too. I had a similar issue with when I was using hand curves before. If i find a fix I'll let you know!

**Comment by insideout-andrew** [comment]
Possible/untested idea: maybe the `card.target_position` should be offset by the `card.pivet_offset`/`card.size * 0.5` or something similar to that.

**Comment by insideout-andrew** [comment]
This issue has been fixed with my latest push. The rotation curve export variable now effects all cards as expected.
